### ISSUE TITLE
Run instructions for jar file?

### ISSUE THREAD

**Issue by newbiemate** [poohcom1/spritesheet-parser#4]
Hello, I downloaded the jar file, but on double clicking it nothing happens. 

Could you please provide instructions on how to run the application?

**Comment by poohcom1** [comment]
Do you have Java installed? It's been a while since I've touched this project xD, so I don't remember if you might need a specific Java version.

As an alternative, you can try out this newer [web version](https://github.com/poohcom1/spritesheet-parser-app) I've made: https://spritesheet-parser.vercel.app/, though it hasn't been thoroughly tested.

**Comment by newbiemate** [comment]
Thanks, I had an old version installed!! I really like this tool, sad to see the old heroku webapp was shut down :D
